name: Android CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write  # 必须显式声明写入权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace
    
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-$(date +%Y%m%d%H%M%S)
        name: Release $(date +'%Y-%m-%d %H:%M')
        files: app/build/outputs/apk/release/*.apk
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}